export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const DAILY_UPDATES_RESET = 'DAILY_UPDATES_RESET';
export const FETCH_DAILY_UPDATES_SUCCESS = 'FETCH_DAILY_UPDATES_SUCCESS';
export const FETCH_DAILY_UPDATES_FAIL = 'FETCH_DAILY_UPDATES_FAIL';
export const FETCH_DAILY_UPDATES_START = 'FETCH_DAILY_UPDATES_START';
export const SUBMIT_DAILY_UPDATES_SUCCESS = 'SUBMIT_DAILY_UPDATES_SUCCESS';
export const SUBMIT_DAILY_UPDATES_FAIL = 'SUBMIT_DAILY_UPDATES_FAIL';
export const SUBMIT_DAILY_UPDATES_START = 'SUBMIT_DAILY_UPDATES_START';
export const DELETE_DAILY_UPDATE_START = 'DELETE_DAILY_UPDATE_START';
export const DELETE_DAILY_UPDATE_SUCCESS = 'DELETE_DAILY_UPDATE_SUCCESS';
export const DELETE_DAILY_UPDATE_FAIL = 'DELETE_TEAM_ROOMS_FAIL';

export const TEAM_ROOMS_RESET = 'TEAM_ROOMS_RESET';
export const FETCH_TEAM_ROOMS_SUCCESS = 'FETCH_TEAM_ROOMS_SUCCESS';
export const FETCH_TEAM_ROOMS_FAIL = 'FETCH_TEAM_ROOMS_FAIL';
export const FETCH_TEAM_ROOMS_START = 'FETCH_TEAM_ROOMS_START';

export const ADD_TEAM_ROOMS_SUCCESS = 'ADD_TEAM_ROOMS_SUCCESS';
export const ADD_TEAM_ROOMS_FAIL = 'ADD_TEAM_ROOMS_FAIL';
export const ADD_TEAM_ROOMS_START = 'ADD_TEAM_ROOMS_START';

export const DELETE_TEAM_ROOMS_START = 'DELETE_TEAM_ROOMS_START';
export const DELETE_TEAM_ROOMS_SUCCESS = 'DELETE_TEAM_ROOMS_SUCCESS';
export const DELETE_TEAM_ROOMS_FAIL = 'DELETE_TEAM_ROOMS_FAIL';
