export const FETCH_DAILY_UPDATES_SUCCESS = 'FETCH_DAILY_UPDATES_SUCCESS';
export const FETCH_DAILY_UPDATES_FAIL = 'FETCH_DAILY_UPDATES_FAIL';
export const FETCH_DAILY_UPDATES_START = 'FETCH_DAILY_UPDATES_START';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
