export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const DAILY_UPDATES_RESET = 'DAILY_UPDATES_RESET';
export const FETCH_DAILY_UPDATES_SUCCESS = 'FETCH_DAILY_UPDATES_SUCCESS';
export const FETCH_DAILY_UPDATES_FAIL = 'FETCH_DAILY_UPDATES_FAIL';
export const FETCH_DAILY_UPDATES_START = 'FETCH_DAILY_UPDATES_START';
export const SUBMIT_DAILY_UPDATES_SUCCESS = 'SUBMIT_DAILY_UPDATES_SUCCESS';
export const SUBMIT_DAILY_UPDATES_FAIL = 'SUBMIT_DAILY_UPDATES_FAIL';
export const SUBMIT_DAILY_UPDATES_START = 'SUBMIT_DAILY_UPDATES_START';
export const DELETE_DAILY_UPDATE_START = 'DELETE_DAILY_UPDATE_START';
export const DELETE_DAILY_UPDATE_SUCCESS = 'DELETE_DAILY_UPDATE_SUCCESS';
export const DELETE_DAILY_UPDATE_FAIL = 'DELETE_DAILY_UPDATE_FAIL';

export const TEAM_ROOMS_RESET = 'TEAM_ROOMS_RESET';
export const FETCH_TEAM_ROOMS_SUCCESS = 'FETCH_TEAM_ROOMS_SUCCESS';
export const FETCH_TEAM_ROOMS_FAIL = 'FETCH_TEAM_ROOMS_FAIL';
export const FETCH_TEAM_ROOMS_START = 'FETCH_TEAM_ROOMS_START';

export const ADD_TEAM_ROOMS_SUCCESS = 'ADD_TEAM_ROOMS_SUCCESS';
export const ADD_TEAM_ROOMS_FAIL = 'ADD_TEAM_ROOMS_FAIL';
export const ADD_TEAM_ROOMS_START = 'ADD_TEAM_ROOMS_START';

export const DELETE_TEAM_ROOMS_START = 'DELETE_TEAM_ROOMS_START';
export const DELETE_TEAM_ROOMS_SUCCESS = 'DELETE_TEAM_ROOMS_SUCCESS';
export const DELETE_TEAM_ROOMS_FAIL = 'DELETE_TEAM_ROOMS_FAIL';

export const USERS_RESET = 'USERS_RESET';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS_START = 'FETCH_USERS_START';

export const ADD_USERS_SUCCESS = 'ADD_USERS_SUCCESS';
export const ADD_USERS_FAIL = 'ADD_USERS_FAIL';
export const ADD_USERS_START = 'ADD_USERS_START';

export const DELETE_USERS_START = 'DELETE_USERS_START';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_FAIL = 'DELETE_USERS_FAIL';

export const RETROSPECTION_RESET = 'RETROSPECTION_RESET';
export const FETCH_RETROSPECTION_SUCCESS = 'FETCH_RETROSPECTION_SUCCESS';
export const FETCH_RETROSPECTION_FAIL = 'FETCH_RETROSPECTION_FAIL';
export const FETCH_RETROSPECTION_START = 'FETCH_RETROSPECTION_START';
export const SUBMIT_RETROSPECTION_SUCCESS = 'SUBMIT_RETROSPECTION_SUCCESS';
export const SUBMIT_RETROSPECTION_FAIL = 'SUBMIT_RETROSPECTION_FAIL';
export const SUBMIT_RETROSPECTION_START = 'SUBMIT_RETROSPECTION_START';
export const DELETE_RETROSPECTION_START = 'DELETE_RETROSPECTION_START';
export const DELETE_RETROSPECTION_SUCCESS = 'DELETE_RETROSPECTION_SUCCESS';
export const DELETE_RETROSPECTION_FAIL = 'DELETE_RETROSPECTION_FAIL';

export const FILTER_SET_START_DATE = 'FILTER_SET_START_DATE';
export const FILTER_SET_END_DATE = 'FILTER_SET_END_DATE';
export const FILTER_SET_NAME = 'FILTER_SET_NAME';
export const FILTER_SET_CALENDAR_FOCUSED = 'FILTER_SET_CALENDAR_FOCUSED';
export const FILTER_SET_TEAM_ROOM = 'FILTER_SET_TEAM_ROOM';
export const FILTER_TOGGLE_SHOW_MINE = 'FILTER_TOGGLE_SHOW_MINE';
export const FILTER_TOGGLE_TABULAR_VIEW = 'FILTER_TOGGLE_TABULAR_VIEW';
